# Generated by Django 2.2.3 on 2019-10-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPoAndPurchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=255)),
                ('Purchaser', models.CharField(max_length=130)),
                ('po_date', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'OrderPoAndPurchasers',
                'db_table': 'poAndPurchaser',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.CharField(max_length=255, null=True)),
                ('items', models.CharField(max_length=100, null=True)),
                ('items_types', models.CharField(max_length=100, null=True)),
                ('quality', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('rate_per_unit', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('dispatcher', models.CharField(max_length=100, null=True)),
                ('dispatch_qty', models.CharField(blank=True, default='', max_length=100)),
                ('dispatch_date', models.CharField(blank=True, default='', max_length=100)),
                ('total_supplied_qty', models.CharField(blank=True, default='', max_length=100)),
                ('balance_qty', models.CharField(blank=True, default='', max_length=100)),
                ('OrderPoAndPurchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderDetails', to='order.OrderPoAndPurchaser')),
            ],
            options={
                'verbose_name_plural': 'OrderDetails',
                'db_table': 'details',
            },
        ),
    ]
