# Generated by Django 2.2.3 on 2019-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='po_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
