# Generated by Django 2.2.3 on 2019-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_dispatch_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='balance_qty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='dispatch_date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='dispatch_qty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='total_supplied_qty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='dispatch',
        ),
    ]
